name: AverageJoes CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: AverageJoes Build and Tests
    strategy:
       matrix:
         java_version: [11]
         os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Java version
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Run tests
      run: sbt test
